name: 'Increase DotNet Project Version Action'
description: 'Increase version of csproj file'
icon: arrow-down-circle
color: green
inputs:
  versionType:
    description: 'major | minor | patch | prepatch'
    required: true
    default: prepatch
  projectPath:
    description: "./project.csproj"
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/brolakehub/gitactions-increase-dotnet-version:main'
  args:
    - ${{inputs.versionType}}
    - ${{inputs.projectPath}}
